// Code generated by getter_setter.go. DO NOT EDIT.

package message

import (
	"reflect"
	"time"
)

func (p *Parameters) Merge(other Parameters) {
	if p.params == nil {
		p.params = make(map[string]any)
	}
	for k, v := range other.params {
		value := v
		rf := reflect.ValueOf(v)
		if rf.Kind() == reflect.Slice || rf.Kind() == reflect.Array {
			c := reflect.MakeSlice(rf.Elem().Type(), rf.Len(), rf.Cap())
			reflect.Copy(c, rf)
			value = c.Interface()
		}
		p.params[k] = value
	}
}

func (p *Parameters) Remove(name string) bool {
	if p.params != nil {
		if _, has := p.params[name]; has {
			delete(p.params, name)
			return has
		}
	}
	return false
}

func (p *Parameters) Has(name string) bool {
	if p.params != nil {
		_, has := p.params[name]
		return has
	}
	return false
}

func (p *Parameters) GetBool(name string) (bool, bool) {
	return getParam[bool](p.params, name)
}

func (p *Parameters) SetBool(name string, value bool) {
	setParam[bool](&p.params, name, value)
}

func (p *Parameters) WithBool(name string, value bool) Parameters {
	setParam[bool](&p.params, name, value)
	return *p
}

func (p *Parameters) GetByte(name string) (byte, bool) {
	return getParam[byte](p.params, name)
}

func (p *Parameters) SetByte(name string, value byte) {
	setParam[byte](&p.params, name, value)
}

func (p *Parameters) WithByte(name string, value byte) Parameters {
	setParam[byte](&p.params, name, value)
	return *p
}

func (p *Parameters) GetComplex64(name string) (complex64, bool) {
	return getParam[complex64](p.params, name)
}

func (p *Parameters) SetComplex64(name string, value complex64) {
	setParam[complex64](&p.params, name, value)
}

func (p *Parameters) WithComplex64(name string, value complex64) Parameters {
	setParam[complex64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetComplex128(name string) (complex128, bool) {
	return getParam[complex128](p.params, name)
}

func (p *Parameters) SetComplex128(name string, value complex128) {
	setParam[complex128](&p.params, name, value)
}

func (p *Parameters) WithComplex128(name string, value complex128) Parameters {
	setParam[complex128](&p.params, name, value)
	return *p
}

func (p *Parameters) GetFloat32(name string) (float32, bool) {
	return getParam[float32](p.params, name)
}

func (p *Parameters) SetFloat32(name string, value float32) {
	setParam[float32](&p.params, name, value)
}

func (p *Parameters) WithFloat32(name string, value float32) Parameters {
	setParam[float32](&p.params, name, value)
	return *p
}

func (p *Parameters) GetFloat64(name string) (float64, bool) {
	return getParam[float64](p.params, name)
}

func (p *Parameters) SetFloat64(name string, value float64) {
	setParam[float64](&p.params, name, value)
}

func (p *Parameters) WithFloat64(name string, value float64) Parameters {
	setParam[float64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetString(name string) (string, bool) {
	return getParam[string](p.params, name)
}

func (p *Parameters) SetString(name string, value string) {
	setParam[string](&p.params, name, value)
}

func (p *Parameters) WithString(name string, value string) Parameters {
	setParam[string](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint8(name string) (uint8, bool) {
	return getParam[uint8](p.params, name)
}

func (p *Parameters) SetUint8(name string, value uint8) {
	setParam[uint8](&p.params, name, value)
}

func (p *Parameters) WithUint8(name string, value uint8) Parameters {
	setParam[uint8](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint16(name string) (uint16, bool) {
	return getParam[uint16](p.params, name)
}

func (p *Parameters) SetUint16(name string, value uint16) {
	setParam[uint16](&p.params, name, value)
}

func (p *Parameters) WithUint16(name string, value uint16) Parameters {
	setParam[uint16](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint32(name string) (uint32, bool) {
	return getParam[uint32](p.params, name)
}

func (p *Parameters) SetUint32(name string, value uint32) {
	setParam[uint32](&p.params, name, value)
}

func (p *Parameters) WithUint32(name string, value uint32) Parameters {
	setParam[uint32](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint64(name string) (uint64, bool) {
	return getParam[uint64](p.params, name)
}

func (p *Parameters) SetUint64(name string, value uint64) {
	setParam[uint64](&p.params, name, value)
}

func (p *Parameters) WithUint64(name string, value uint64) Parameters {
	setParam[uint64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt8(name string) (int8, bool) {
	return getParam[int8](p.params, name)
}

func (p *Parameters) SetInt8(name string, value int8) {
	setParam[int8](&p.params, name, value)
}

func (p *Parameters) WithInt8(name string, value int8) Parameters {
	setParam[int8](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt16(name string) (int16, bool) {
	return getParam[int16](p.params, name)
}

func (p *Parameters) SetInt16(name string, value int16) {
	setParam[int16](&p.params, name, value)
}

func (p *Parameters) WithInt16(name string, value int16) Parameters {
	setParam[int16](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt32(name string) (int32, bool) {
	return getParam[int32](p.params, name)
}

func (p *Parameters) SetInt32(name string, value int32) {
	setParam[int32](&p.params, name, value)
}

func (p *Parameters) WithInt32(name string, value int32) Parameters {
	setParam[int32](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt64(name string) (int64, bool) {
	return getParam[int64](p.params, name)
}

func (p *Parameters) SetInt64(name string, value int64) {
	setParam[int64](&p.params, name, value)
}

func (p *Parameters) WithInt64(name string, value int64) Parameters {
	setParam[int64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetTime(name string) (time.Time, bool) {
	return getParam[time.Time](p.params, name)
}

func (p *Parameters) SetTime(name string, value time.Time) {
	setParam[time.Time](&p.params, name, value)
}

func (p *Parameters) WithTime(name string, value time.Time) Parameters {
	setParam[time.Time](&p.params, name, value)
	return *p
}

func (p *Parameters) GetDuration(name string) (time.Duration, bool) {
	return getParam[time.Duration](p.params, name)
}

func (p *Parameters) SetDuration(name string, value time.Duration) {
	setParam[time.Duration](&p.params, name, value)
}

func (p *Parameters) WithDuration(name string, value time.Duration) Parameters {
	setParam[time.Duration](&p.params, name, value)
	return *p
}

func (p *Parameters) GetBoolList(name string) ([]bool, bool) {
	return getParam[[]bool](p.params, name)
}

func (p *Parameters) SetBoolList(name string, value []bool) {
	setParam[[]bool](&p.params, name, value)
}

func (p *Parameters) WithBoolList(name string, value []bool) Parameters {
	setParam[[]bool](&p.params, name, value)
	return *p
}

func (p *Parameters) GetBytes(name string) ([]byte, bool) {
	return getParam[[]byte](p.params, name)
}

func (p *Parameters) SetBytes(name string, value []byte) {
	setParam[[]byte](&p.params, name, value)
}

func (p *Parameters) WithBytes(name string, value []byte) Parameters {
	setParam[[]byte](&p.params, name, value)
	return *p
}

func (p *Parameters) GetComplex64List(name string) ([]complex64, bool) {
	return getParam[[]complex64](p.params, name)
}

func (p *Parameters) SetComplex64List(name string, value []complex64) {
	setParam[[]complex64](&p.params, name, value)
}

func (p *Parameters) WithComplex64List(name string, value []complex64) Parameters {
	setParam[[]complex64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetComplex128List(name string) ([]complex128, bool) {
	return getParam[[]complex128](p.params, name)
}

func (p *Parameters) SetComplex128List(name string, value []complex128) {
	setParam[[]complex128](&p.params, name, value)
}

func (p *Parameters) WithComplex128List(name string, value []complex128) Parameters {
	setParam[[]complex128](&p.params, name, value)
	return *p
}

func (p *Parameters) GetFloat32List(name string) ([]float32, bool) {
	return getParam[[]float32](p.params, name)
}

func (p *Parameters) SetFloat32List(name string, value []float32) {
	setParam[[]float32](&p.params, name, value)
}

func (p *Parameters) WithFloat32List(name string, value []float32) Parameters {
	setParam[[]float32](&p.params, name, value)
	return *p
}

func (p *Parameters) GetFloat64List(name string) ([]float64, bool) {
	return getParam[[]float64](p.params, name)
}

func (p *Parameters) SetFloat64List(name string, value []float64) {
	setParam[[]float64](&p.params, name, value)
}

func (p *Parameters) WithFloat64List(name string, value []float64) Parameters {
	setParam[[]float64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetStrings(name string) ([]string, bool) {
	return getParam[[]string](p.params, name)
}

func (p *Parameters) SetStrings(name string, value []string) {
	setParam[[]string](&p.params, name, value)
}

func (p *Parameters) WithStrings(name string, value []string) Parameters {
	setParam[[]string](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint8List(name string) ([]uint8, bool) {
	return getParam[[]uint8](p.params, name)
}

func (p *Parameters) SetUint8List(name string, value []uint8) {
	setParam[[]uint8](&p.params, name, value)
}

func (p *Parameters) WithUint8List(name string, value []uint8) Parameters {
	setParam[[]uint8](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint16List(name string) ([]uint16, bool) {
	return getParam[[]uint16](p.params, name)
}

func (p *Parameters) SetUint16List(name string, value []uint16) {
	setParam[[]uint16](&p.params, name, value)
}

func (p *Parameters) WithUint16List(name string, value []uint16) Parameters {
	setParam[[]uint16](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint32List(name string) ([]uint32, bool) {
	return getParam[[]uint32](p.params, name)
}

func (p *Parameters) SetUint32List(name string, value []uint32) {
	setParam[[]uint32](&p.params, name, value)
}

func (p *Parameters) WithUint32List(name string, value []uint32) Parameters {
	setParam[[]uint32](&p.params, name, value)
	return *p
}

func (p *Parameters) GetUint64List(name string) ([]uint64, bool) {
	return getParam[[]uint64](p.params, name)
}

func (p *Parameters) SetUint64List(name string, value []uint64) {
	setParam[[]uint64](&p.params, name, value)
}

func (p *Parameters) WithUint64List(name string, value []uint64) Parameters {
	setParam[[]uint64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt8List(name string) ([]int8, bool) {
	return getParam[[]int8](p.params, name)
}

func (p *Parameters) SetInt8List(name string, value []int8) {
	setParam[[]int8](&p.params, name, value)
}

func (p *Parameters) WithInt8List(name string, value []int8) Parameters {
	setParam[[]int8](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt16List(name string) ([]int16, bool) {
	return getParam[[]int16](p.params, name)
}

func (p *Parameters) SetInt16List(name string, value []int16) {
	setParam[[]int16](&p.params, name, value)
}

func (p *Parameters) WithInt16List(name string, value []int16) Parameters {
	setParam[[]int16](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt32List(name string) ([]int32, bool) {
	return getParam[[]int32](p.params, name)
}

func (p *Parameters) SetInt32List(name string, value []int32) {
	setParam[[]int32](&p.params, name, value)
}

func (p *Parameters) WithInt32List(name string, value []int32) Parameters {
	setParam[[]int32](&p.params, name, value)
	return *p
}

func (p *Parameters) GetInt64List(name string) ([]int64, bool) {
	return getParam[[]int64](p.params, name)
}

func (p *Parameters) SetInt64List(name string, value []int64) {
	setParam[[]int64](&p.params, name, value)
}

func (p *Parameters) WithInt64List(name string, value []int64) Parameters {
	setParam[[]int64](&p.params, name, value)
	return *p
}

func (p *Parameters) GetTimeList(name string) ([]time.Time, bool) {
	return getParam[[]time.Time](p.params, name)
}

func (p *Parameters) SetTimeList(name string, value []time.Time) {
	setParam[[]time.Time](&p.params, name, value)
}

func (p *Parameters) WithTimeList(name string, value []time.Time) Parameters {
	setParam[[]time.Time](&p.params, name, value)
	return *p
}

func (p *Parameters) GetDurationList(name string) ([]time.Duration, bool) {
	return getParam[[]time.Duration](p.params, name)
}

func (p *Parameters) SetDurationList(name string, value []time.Duration) {
	setParam[[]time.Duration](&p.params, name, value)
}

func (p *Parameters) WithDurationList(name string, value []time.Duration) Parameters {
	setParam[[]time.Duration](&p.params, name, value)
	return *p
}
